/**
 * @module core/indexing/scanner
 * @description 파일 스캐너 - 프로젝트 디렉토리를 스캔하여 파일 목록 생성
 */

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import fg from 'fast-glob';
import ignore, { Ignore } from 'ignore';
import { FileInfo } from '../../types/index';
import { ScanResult } from './types';
import { logger } from '../../utils/logger';

/** 지원하는 파일 확장자 */
const SUPPORTED_EXTENSIONS = ['.ts', '.tsx', '.js', '.jsx', '.vue', '.java', '.kt', '.py'];

/** 기본 무시 패턴 */
const DEFAULT_IGNORE_PATTERNS = [
  'node_modules/**',
  '.git/**',
  'dist/**',
  'build/**',
  'coverage/**',
  '.next/**',
  '.nuxt/**',
  '__pycache__/**',
  '*.min.js',
  '*.min.css',
  '*.map',
  '*.d.ts',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
];

/** 확장자별 언어 매핑 */
const EXTENSION_LANGUAGE_MAP: Record<string, string> = {
  '.ts': 'TypeScript',
  '.tsx': 'TypeScript (JSX)',
  '.js': 'JavaScript',
  '.jsx': 'JavaScript (JSX)',
  '.vue': 'Vue',
  '.java': 'Java',
  '.kt': 'Kotlin',
  '.py': 'Python',
};

/** 자동 생성 파일 패턴 */
const AUTO_GENERATED_FILE_PATTERNS = [
  /\.generated\./i,
  /\.g\.dart$/i,
  /\.pb\.java$/i,
  /\.pb\.kt$/i,
  /_pb2\.py$/i,
  /\.freezed\.dart$/i,
  /\.min\.js$/i,
  /\.min\.css$/i,
];

/** 자동 생성 콘텐츠 마커 */
const AUTO_GENERATED_CONTENT_MARKERS = [
  '@Generated',
  '@javax.annotation.Generated',
  'auto-generated',
  'DO NOT EDIT',
  'This file is automatically generated',
  'Code generated by',
];


/**
 * FileScanner - 프로젝트 디렉토리를 스캔하여 파일 목록 생성
 *
 * 기능:
 *   - fast-glob을 사용한 파일 탐색
 *   - .gitignore 패턴 적용
 *   - 기술 스택 자동 감지
 *   - 파일별 SHA-256 해시 생성
 */
export class FileScanner {
  /**
   * 프로젝트 디렉토리를 스캔하여 파일 목록 생성
   * @param projectPath - 프로젝트 루트 경로
   * @returns 스캔 결과
   */
  async scan(projectPath: string): Promise<ScanResult> {
    const resolvedPath = path.resolve(projectPath);

    if (!fs.existsSync(resolvedPath)) {
      throw new Error(`Project path does not exist: ${resolvedPath}`);
    }

    if (!fs.statSync(resolvedPath).isDirectory()) {
      throw new Error(`Project path is not a directory: ${resolvedPath}`);
    }

    logger.info(`Scanning project: ${resolvedPath}`);

    // .gitignore 패턴 로드
    const ig = this.loadIgnorePatterns(resolvedPath);

    // 지원하는 확장자의 glob 패턴 생성
    const extensionPatterns = SUPPORTED_EXTENSIONS.map(ext => `**/*${ext}`);

    // fast-glob으로 파일 탐색
    const filePaths = await fg(extensionPatterns, {
      cwd: resolvedPath,
      absolute: false,
      dot: false,
      onlyFiles: true,
      ignore: DEFAULT_IGNORE_PATTERNS,
    });

    // .gitignore 필터 적용
    const filteredPaths = filePaths.filter(fp => !ig.ignores(fp));

    // 파일 정보 수집
    const files: FileInfo[] = [];
    let totalLines = 0;
    const languages: Record<string, number> = {};

    let skippedAutoGenerated = 0;

    for (const relativePath of filteredPaths) {
      // TASK-019: 자동 생성 파일 패턴 검사 (파일명 기반)
      if (this.isAutoGeneratedFile(relativePath)) {
        skippedAutoGenerated++;
        logger.debug(`Skipped auto-generated file (filename pattern): ${relativePath}`);
        continue;
      }

      const absolutePath = path.join(resolvedPath, relativePath);
      try {
        const stat = fs.statSync(absolutePath);
        const content = fs.readFileSync(absolutePath, 'utf-8');

        // TASK-019: 자동 생성 파일 콘텐츠 마커 검사
        if (this.isAutoGeneratedContent(content)) {
          skippedAutoGenerated++;
          logger.debug(`Skipped auto-generated file (content marker): ${relativePath}`);
          continue;
        }

        const lineCount = this.countLines(content);
        totalLines += lineCount;

        const ext = path.extname(relativePath);
        const lang = EXTENSION_LANGUAGE_MAP[ext] || ext;
        languages[lang] = (languages[lang] || 0) + 1;

        const hash = this.computeFileHashFromContent(content);

        files.push({
          path: relativePath,
          hash,
          size: stat.size,
          extension: ext,
          lastModified: stat.mtime.toISOString(),
        });
      } catch (err) {
        logger.warn(`Failed to process file: ${relativePath}`, err);
      }
    }

    // 기술 스택 감지
    const techStack = await this.detectTechStack(resolvedPath);

    if (skippedAutoGenerated > 0) {
      logger.info(`Skipped ${skippedAutoGenerated} auto-generated files`);
    }
    logger.info(`Scan complete: ${files.length} files, ${totalLines} lines`);

    return {
      files,
      techStack,
      stats: {
        totalFiles: files.length,
        totalLines,
        languages,
      },
    };
  }

  /**
   * .gitignore 패턴 로드 및 적용
   * @param projectPath - 프로젝트 루트 경로
   * @returns ignore 인스턴스
   */
  private loadIgnorePatterns(projectPath: string): Ignore {
    const ig = ignore();
    const gitignorePath = path.join(projectPath, '.gitignore');

    if (fs.existsSync(gitignorePath)) {
      try {
        const content = fs.readFileSync(gitignorePath, 'utf-8');
        const patterns = content
          .split('\n')
          .map(line => line.trim())
          .filter(line => line && !line.startsWith('#'));
        ig.add(patterns);
        logger.debug(`Loaded ${patterns.length} .gitignore patterns`);
      } catch (err) {
        logger.warn('Failed to read .gitignore', err);
      }
    }

    return ig;
  }

  /**
   * 기술 스택 자동 감지
   * @param projectPath - 프로젝트 루트 경로
   * @returns 감지된 기술 스택 목록
   */
  private async detectTechStack(projectPath: string): Promise<string[]> {
    const techStack: string[] = [];

    // package.json 분석
    const packageJsonPath = path.join(projectPath, 'package.json');
    if (fs.existsSync(packageJsonPath)) {
      try {
        const content = fs.readFileSync(packageJsonPath, 'utf-8');
        const pkg = JSON.parse(content) as {
          dependencies?: Record<string, string>;
          devDependencies?: Record<string, string>;
        };
        const allDeps = {
          ...pkg.dependencies,
          ...pkg.devDependencies,
        };

        // 프레임워크/라이브러리 감지
        if (allDeps['react']) techStack.push('React');
        if (allDeps['react-dom']) techStack.push('React DOM');
        if (allDeps['next']) techStack.push('Next.js');
        if (allDeps['vue']) techStack.push('Vue.js');
        if (allDeps['nuxt']) techStack.push('Nuxt.js');
        if (allDeps['@angular/core']) techStack.push('Angular');
        if (allDeps['express']) techStack.push('Express');
        if (allDeps['fastify']) techStack.push('Fastify');
        if (allDeps['nestjs'] || allDeps['@nestjs/core']) techStack.push('NestJS');
        if (allDeps['typescript']) techStack.push('TypeScript');
        if (allDeps['tailwindcss']) techStack.push('Tailwind CSS');
        if (allDeps['axios']) techStack.push('Axios');
        if (allDeps['react-router'] || allDeps['react-router-dom']) techStack.push('React Router');
        if (allDeps['redux'] || allDeps['@reduxjs/toolkit']) techStack.push('Redux');
        if (allDeps['zustand']) techStack.push('Zustand');
        if (allDeps['prisma'] || allDeps['@prisma/client']) techStack.push('Prisma');
        if (allDeps['typeorm']) techStack.push('TypeORM');
        if (allDeps['jest']) techStack.push('Jest');
        if (allDeps['vitest']) techStack.push('Vitest');
      } catch (err) {
        logger.warn('Failed to parse package.json', err);
      }
    }

    // build.gradle 분석 (Java/Kotlin)
    const gradlePath = path.join(projectPath, 'build.gradle');
    const gradleKtsPath = path.join(projectPath, 'build.gradle.kts');
    if (fs.existsSync(gradlePath) || fs.existsSync(gradleKtsPath)) {
      techStack.push('Gradle');
      const gradleFile = fs.existsSync(gradleKtsPath) ? gradleKtsPath : gradlePath;
      try {
        const content = fs.readFileSync(gradleFile, 'utf-8');
        if (content.includes('spring-boot')) techStack.push('Spring Boot');
        if (content.includes('kotlin')) techStack.push('Kotlin');
      } catch {
        // ignore
      }
    }

    // pom.xml 분석 (Java)
    if (fs.existsSync(path.join(projectPath, 'pom.xml'))) {
      techStack.push('Maven');
    }

    // requirements.txt / pyproject.toml (Python)
    if (fs.existsSync(path.join(projectPath, 'requirements.txt'))) {
      techStack.push('Python');
    }
    if (fs.existsSync(path.join(projectPath, 'pyproject.toml'))) {
      techStack.push('Python');
    }

    // tsconfig.json
    if (fs.existsSync(path.join(projectPath, 'tsconfig.json'))) {
      if (!techStack.includes('TypeScript')) {
        techStack.push('TypeScript');
      }
    }

    return [...new Set(techStack)];
  }

  /**
   * 콘텐츠 기반 SHA-256 해시 생성 (이중 파일 읽기 제거)
   * @param content - 파일 콘텐츠 문자열
   * @returns SHA-256 해시 문자열
   */
  private computeFileHashFromContent(content: string): string {
    const hash = crypto.createHash('sha256');
    hash.update(content, 'utf-8');
    return hash.digest('hex');
  }

  /**
   * 자동 생성 파일 여부를 파일명 패턴으로 판별
   * @param filePath - 상대 파일 경로
   * @returns 자동 생성 파일이면 true
   */
  private isAutoGeneratedFile(filePath: string): boolean {
    return AUTO_GENERATED_FILE_PATTERNS.some(pattern => pattern.test(filePath));
  }

  /**
   * 자동 생성 파일 여부를 콘텐츠 마커로 판별 (처음 20줄 검사)
   * @param content - 파일 콘텐츠 문자열
   * @returns 자동 생성 콘텐츠이면 true
   */
  private isAutoGeneratedContent(content: string): boolean {
    const first20Lines = content.split('\n').slice(0, 20).join('\n');
    return AUTO_GENERATED_CONTENT_MARKERS.some(marker => first20Lines.includes(marker));
  }

  /**
   * 메모리 할당 없이 라인 수를 세는 최적화된 메서드
   * content.split('\n').length 대비 메모리 할당 제거
   * @param content - 파일 콘텐츠 문자열
   * @returns 라인 수
   */
  private countLines(content: string): number {
    let count = 1;
    for (let i = 0; i < content.length; i++) {
      if (content[i] === '\n') {
        count++;
      }
    }
    return count;
  }
}
